# Generated by Django 5.0 on 2024-12-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('vendor', 'Vendor Master'), ('item', 'Item Master'), ('purchase', 'Purchase History'), ('contract', 'Contracts'), ('facility', 'Facilities'), ('department', 'Departments')], max_length=20)),
                ('description', models.TextField()),
                ('required_headers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('vendor', 'Vendor Master'), ('item', 'Item Master'), ('purchase', 'Purchase History'), ('contract', 'Contracts'), ('facility', 'Facilities'), ('department', 'Departments')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
