# Generated by Django 5.0 on 2024-12-19 21:41

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatemplate',
            name='template_type',
            field=models.CharField(choices=[('vendor', 'Vendor Master'), ('item', 'Item Master'), ('purchase', 'Purchase History'), ('invoice', 'Invoice Data'), ('contract', 'Contracts'), ('facility', 'Facilities'), ('department', 'Departments')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='file',
            field=models.FileField(upload_to=collection.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='template_type',
            field=models.CharField(choices=[('vendor', 'Vendor Master'), ('item', 'Item Master'), ('purchase', 'Purchase History'), ('invoice', 'Invoice Data'), ('contract', 'Contracts'), ('facility', 'Facilities'), ('department', 'Departments')], default='vendor', max_length=20),
        ),
    ]
