# Generated by Django 5.0 on 2024-12-24 00:37

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_initial_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatemplate',
            options={'ordering': ['name'], 'verbose_name': 'Data Template', 'verbose_name_plural': 'Data Templates'},
        ),
        migrations.AlterModelOptions(
            name='dataupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Data Upload', 'verbose_name_plural': 'Data Uploads'},
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='file',
            field=models.FileField(max_length=255, upload_to=collection.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='validation_errors',
            field=models.JSONField(blank=True, help_text='Stores validation errors if any', null=True),
        ),
    ]
