# Generated by Django 5.0 on 2024-12-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_datatemplate_options_alter_dataupload_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about the upload', null=True),
        ),
    ]
