# Generated by Django 5.0 on 2024-12-24 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_dataupload_data_type_dataupload_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
